name: NPM Package
# on: 
#   push:
#     branches: 
#       - main
#     tags:
#       - v*
on: push

jobs:
  setup:
    name: Setup the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Use Node modules cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package.json') }}
          restore-keys: npm-deps-
      - name: Install dependencies
        run: npm install
  test:
    needs: setup
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - run: npm test
  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


